// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuoheeQgOtJEoi-tArncPHxFIJk4k2lLo',
    appId: '1:218311539230:web:d78e42e309da9fed238c0f',
    messagingSenderId: '218311539230',
    projectId: 'chat-app-flutter-project-4f8c4',
    authDomain: 'chat-app-flutter-project-4f8c4.firebaseapp.com',
    storageBucket: 'chat-app-flutter-project-4f8c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBREM8dI2voVziLXGVQ7qFafsSNmoV0YhU',
    appId: '1:218311539230:android:f0030f700de0d4d0238c0f',
    messagingSenderId: '218311539230',
    projectId: 'chat-app-flutter-project-4f8c4',
    storageBucket: 'chat-app-flutter-project-4f8c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrvMgkMdF04onECOpyvFBb4-bqhljB_Xs',
    appId: '1:218311539230:ios:facecaebdf6aff56238c0f',
    messagingSenderId: '218311539230',
    projectId: 'chat-app-flutter-project-4f8c4',
    storageBucket: 'chat-app-flutter-project-4f8c4.appspot.com',
    iosBundleId: 'com.example.trialChat',
  );
}
